# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: en-US
early_access: false
enable_free_tier: true

reviews:
  profile: chill
  high_level_summary: true
  high_level_summary_in_walkthrough: false
  review_status: true
  commit_status: true
  request_changes_workflow: false
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false
  path_filters:
    - "cmd/**"
    - "internal/**"
    - "migrations/**"
    - "tests/**"
    - "go.mod"
    - "go.sum"
    - "Makefile"
    - ".github/**"
    - "!bin/**"

chat:
  auto_reply: true

knowledge_base:
  learnings:
    scope: auto
