ALTER TABLE users
    ADD COLUMN IF NOT EXISTS bio TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS phone_number TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS name_color TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS saved_tracks JSONB NOT NULL DEFAULT '[]'::jsonb;