-- Share links for chat folders (dialog filters, migration 000041): the owner of
-- a folder mints a token that lets any signed-in user preview the folder
-- contents (name, icon, chats with per-chat membership flags). The server
-- never auto-joins on resolve; the client shows an import dialog instead.
--
-- token:      32 hex chars (16 bytes of crypto/rand), generated by the
--             service layer, globally unique.
-- revoked_at: NULL while the link is live; set to now() when the owner
--             revokes it. At most one live link exists per folder, enforced by
--             the partial unique index below, so re-creating returns the
--             active token instead of minting a second one.
-- use_count:  incremented (best effort) on every successful resolve.
CREATE TABLE IF NOT EXISTS chat_folder_invites (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    folder_id UUID NOT NULL REFERENCES chat_folders(id) ON DELETE CASCADE,
    token TEXT NOT NULL UNIQUE,
    created_by UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    revoked_at TIMESTAMPTZ NULL,
    use_count INTEGER NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_chat_folder_invites_folder_active
    ON chat_folder_invites (folder_id) WHERE revoked_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_chat_folder_invites_token ON chat_folder_invites (token);
